[project]
name = "dataset-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.3.2",
    "huggingface-hub[cli]>=0.29.1",
    "pyarrow>=19.0.1",
]
